// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "5838a98c-f603-4cb4-bbce-7fddcf1ce394";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onBabaMessagerChange();
void onSensorSomChange();
void onSensorTemperaturaChange();
void onSensorUmidadeChange();
void onSensorDigitalSomChange();

String babaMessager;
int sensorSom;
int sensorTemperatura;
int sensorUmidade;
bool sensorDigitalSom;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(babaMessager, READWRITE, ON_CHANGE, onBabaMessagerChange);
  ArduinoCloud.addProperty(sensorSom, READWRITE, ON_CHANGE, onSensorSomChange);
  ArduinoCloud.addProperty(sensorTemperatura, READWRITE, ON_CHANGE, onSensorTemperaturaChange);
  ArduinoCloud.addProperty(sensorUmidade, READWRITE, ON_CHANGE, onSensorUmidadeChange);
  ArduinoCloud.addProperty(sensorDigitalSom, READWRITE, ON_CHANGE, onSensorDigitalSomChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
